spring.application.name=zaran_design_backend

spring.datasource.url=jdbc:mysql://localhost:3306/404N
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT配置
jwt.secret=zaran-design-backend-secret-key-2026-for-course-project
jwt.access-token-expiration=7200
jwt.refresh-token-expiration=604800

# 设置单个文件最大支持 20MB
spring.servlet.multipart.max-file-size=20MB
# 设置单次请求最大支持 20MB
spring.servlet.multipart.max-request-size=20MB