POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "phone": "13372668656"

}

### 测试 1：获取 1 号知识点关联的图案列表
GET http://localhost:8088/api/knowledge/entries/1/related-patterns
Accept: application/json

### 测试 2：模拟 3 号普通游客用户，收藏 1 号知识点并写下笔记
POST http://localhost:8088/api/knowledge/entries/1/notes
Content-Type: application/json

{
  "userId": 3,
  "personalNote": "这个浸染手法太赞了，下次协同创作可以用上！"
}


### 动作 1：先查看目前有多少“待审核”的知识
GET http://localhost:8088/api/knowledge/entries/pending

### 动作 2：传承人觉得这篇写得好，点击“审核通过”
# （假设动作1中查出来的某条待审核知识的 entryId 是 6，请把下面 URL 里的 6 换成你查到的真实 ID）
PUT http://localhost:8088/api/knowledge/entries/6/approve

### 动作 3：去“已发布”列表里看看，是不是多了一篇刚才通过的文章！
GET http://localhost:8088/api/knowledge/entries

### 测试图片上传 (注意：请把底下那行路径改成你电脑上一张真实图片的路径)
POST http://localhost:8088/api/upload/image
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< "C:\Users\沙小光\Desktop\bb72fd8bf167fb3b8ab65ea737925c04.png"
--WebAppBoundary--